# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
